# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gurl < Formula
  desc "gURL is a tool to transfer data from or to a server!"
  homepage "https://gurl.academic.io/"
  version "v2021.06.08"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/academic/gURL/releases/download/v2021.06.08/gURL_2021.06.08_darwin_amd64.tar.gz"
    sha256 "e651344ecc5b14b9b48592ac3dafb39fc971ac9f4b96c5950de8fe410ed3dbc5"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/academic/gURL/releases/download/v2021.06.08/gURL_2021.06.08_darwin_arm64.tar.gz"
    sha256 "59cb46dcf47131114b933231d7a607929987e06a050cb9f09c12de371658e596"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/academic/gURL/releases/download/v2021.06.08/gURL_2021.06.08_linux_amd64.tar.gz"
    sha256 "b46129dbd54d6dcfc919197388f1239272c7ed0cbbfe9ed56eb5f4cbaf1593d4"
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "gurl"
  end

  def caveats; <<~EOS
    gURL is a tool to transfer data from or to a server, using one of the supported protocols (DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET and TFTP). The command is designed to work without user interaction.
  EOS
  end
end
